

SAMPLE_RATE = 48000
CHUNK_SECONDS = 1.0
CHUNK_SAMPLES = int(SAMPLE_RATE * CHUNK_SECONDS)

MIX_PREFIX_FRAMES = 16
LEFT_EDGE_FRAMES_TO_REMOVE = 8
assert LEFT_EDGE_FRAMES_TO_REMOVE <= MIX_PREFIX_FRAMES
